### ISSUE TITLE
CloudFormation template hangs indefinitely in Module0- Environment Setup

### ISSUE THREAD

**Issue by DevoKun** [aws-samples/aws-container-devsecops-workshop#26]
In Module 0, the Cloudformation template hangs indefinitely during Environment setup. The nested template `AnchoreStack` hangs while creating the resource `AnchoreFargateService`.

```
https://container-devsecops.awssecworkshops.com/00-env-setup/
  ↳ https://s3.us-east-2.amazonaws.com/sa-security-specialist-workshops-us-east-2/devsecops/containers/container-devsecops-workshop.yml
      ↳ https://s3.us-east-2.amazonaws.com/sa-security-specialist-workshops-us-east-2/devsecops/containers/anchore-fargate.yml
```

The issue appears to be that the stack requires a container image to be created by `InitialPipeline` which depends on `AnchoreStack` to complete. Because the two have cyclical dependencies, they will never complete unless you manually edit the service created by `AnchoreStack` so that the Cloudformation can continue.

```yaml
Resources:

  AnchoreVpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        EnvironmentName: container-devsecops-wksp
      TemplateURL: !Join [ '/', [ 'https://s3.amazonaws.com', !Ref BucketName, 'devsecops/containers/anchore-vpc.yml'  ] ]

  AnchoreStack:
    DependsOn: AnchoreVpcStack
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ResourceName: container-devsecops-wksp
        BucketName: !Ref BucketName
      TemplateURL: !Join [ '/', [ 'https://s3.amazonaws.com', !Ref BucketName, 'devsecops/containers/anchore-fargate.yml'  ] ]

  InitialPipeline:
    DependsOn: AnchoreStack
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ResourceName: container-devsecops-wksp
        FailWhen: High
        BucketName: !Ref BucketName
      TemplateURL: !Join [ '/', [ 'https://s3.amazonaws.com', !Ref BucketName, 'devsecops/containers/pipeline-setup.yml'  ] ]
```
